#!/bin/sh
ALIAS_CMD="${0#/sbin/}"

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        exec service "$1" "$ALIAS_CMD"
        ;;
esac

case "$1" in
    list)
        exec service --status-all
        ;;
    reload-configuration)
        exec service "$2" restart
        ;;
    start|stop|restart|reload|status)
        exec service "$2" "$1"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|list|reload-configuration}" >&2
        exit 1
        ;;
esac
