name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read
  packages: write
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: afreisinger/build-push-action@v1.1.0
        with:
          image-name: docker-ubuntu2204-ansible
          authors: 'Adrián Freisinger <afreisinger@gmail.com>'
          maintainers: 'Adrián Freisinger <afreisinger@gmail.com>'
          vendor: 'Adrián Freisinger'
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-pat: ${{ secrets.DOCKER_PAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dockerhub: true
          publish-ghcr: true
